services:
  db:
    image: postgres:15-alpine
    container_name: strix_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Qwe.123*}
      POSTGRES_DB: ${POSTGRES_DB:-strix_final}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: strix_app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-Qwe.123*}@db:5432/${POSTGRES_DB:-strix_final}
    # Se agregaron los puertos para exponer la API (Swagger)
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./artifacts:/app/artifacts
      - ./Data:/app/Data
    stdin_open: true 
    tty: true
    # Se define el comando de inicio para ejecutar la API
    command: python src/main_api.py

volumes:
  postgres_data: